### ISSUE TITLE
Version of WpfHexaEditorControl target framework ".NETFramework,Version=v4.6" ?

### ISSUE THREAD

**Issue by Aitania** [abbaye/WpfHexEditorControl#22]
## Expected Behavior
<control:HexEditor/>

## Actual Behavior
 warning MSB3274: The primary reference "WPFHexaEditor" could not be resolved because it was built against the ".NETFramework,Version=v4.7.1" framework. This is a higher version than the currently targeted framework ".NETFramework,Version=v4.6".
error MC3074: The tag 'HexEditor' does not exist in XML namespace 'clr-namespace:WpfHexaEditor;assembly=WPFHexaEditor'

## Steps to Reproduce the Problem

 I made a reference to WPFHexaEditor.dll in a 4.6 .Net project...  The tag 'HexEditor' does not exist in XML namespace 
 I have build a release with visual studio 2015 using the Microsoft.Net.Compilers package.
That does not help as well

Is it possible to create a 4.6 .Net dll sample or dll as well?

Thanks!

**Comment by abbaye** [comment]
Hi aitania
You need to change your target framework to 4.7 minimum 
This will correct your problem :)
Regards
Envoyé de mon appareil Samsung de Bell via le réseau le plus vaste au pays.
-------- Message d'origine --------De : Aitania <notifications@github.com> Date : 18-01-20  16:02  (GMT-05:00) À : abbaye/WpfHexEditorControl <WpfHexEditorControl@noreply.github.com> Cc : Subscribed <subscribed@noreply.github.com> Objet : [abbaye/WpfHexEditorControl] error MC3074: The tag 'HexEditor' does not exist in XML namespace 'clr-namespace:WpfHexaEditor;assembly=WPFHexaEditor' (#22) 
Expected Behavior
control:HexEditor/
Actual Behavior
warning MSB3274: The primary reference "WPFHexaEditor" could not be resolved because it was built against the ".NETFramework,Version=v4.7.1" framework. This is a higher version than the currently targeted framework ".NETFramework,Version=v4.6".

error MC3074: The tag 'HexEditor' does not exist in XML namespace 'clr-namespace:WpfHexaEditor;assembly=WPFHexaEditor'
Steps to Reproduce the Problem
I made a reference to WPFHexaEditor.dll in a 4.6 .Net project...  The tag 'HexEditor' does not exist in XML namespace

I have build a release with visual studio 2015 using the Microsoft.Net.Compilers package.

That does not help as well
Is it possible to create a 4.6 .Net dll sample or dll as well?
Thanks!

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/abbaye/WpfHexEditorControl","title":"abbaye/WpfHexEditorControl","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/abbaye/WpfHexEditorControl"}},"updates":{"snippets":[{"icon":"DESCRIPTION","message":"error MC3074: The tag 'HexEditor' does not exist in XML namespace 'clr-namespace:WpfHexaEditor;assembly=WPFHexaEditor' (#22)"}],"action":{"name":"View Issue","url":"https://github.com/abbaye/WpfHexEditorControl/issues/22"}}}

**Comment by abbaye** [comment]
I can't create 4.6 package because my code use c# 7.0...

**Comment by abbaye** [comment]
I can't create 4.6 package because my code use c# 7.0...

**Comment by abbaye** [comment]
I can't create 4.6 package because my code use c# 7.0...

**Comment by Aitania** [comment]
Hallo,
thanks for the quick answer. 
I have a project which is build with 4.6 framework. 
Anyway. When i reference the HexaEditor in my XAML i get this error:

error MC3074: The tag 'HexEditor' does not exist in XML namespace 'clr-namespace:WpfHexaEditor;assembly=WPFHexaEditor'

I think its because my project uses the 4.6 framework!?

**Comment by abbaye** [comment]
Hello.

Yes it's because your project use 4.6  you can upgrade your framework to 4.7.1 with no problem.

You can change the framework of my project but you will need to  reference nuget package System.ValueTuple

**Comment by Aitania** [comment]
Thank you Derek!!!

**Comment by abbaye** [comment]
Its work ? :)

**Comment by Aitania** [comment]
No. I have tried this:
i use vs 2015
i open the project in a lower framework release 4.5.2 
I removed non WPF sample projects
i referenced the System.ValueTuple assembly
I change the framework to 4.6.. 
Build error:
1>------ Build started: Project: WPFHexaEditor, Configuration: Debug Any CPU ------
1>CSC : error CS1617: Invalid option 'latest' for /langversion; must be ISO-1, ISO-2, Default or an integer in range 1 to 6.
2>------ Build started: Project: WpfHexEditor.Sample, Configuration: Debug Any CPU ------
2>C:\__Codeproject\_HEX-Editor\WpfHexEditorControl-master\WPFHexaEditorExample\MainWindow.xaml(225,18): error MC3074: The tag 'HexBox' does not exist in XML namespace 'clr-namespace:WpfHexaEditor;assembly=WPFHexaEditor'. Line 225 Position 18.
========== Build: 0 succeeded, 2 failed, 0 up-to-date, 0 skipped ==========

**Comment by abbaye** [comment]
Unfortunately visual studio 2015 can't compile c# 7.0 code... 

You can compile project in visual studio 2017 and after reference the dll in your project in vs2015

Another option is to use the nuget version 1.2.1 (less optimised and less functionality)

**Comment by Aitania** [comment]
I have already tried both ways with no success.
I dont have  visual studio 2017
i have tried the version 1.2.1 even if the latest version is very nice, (you have done a very good work)
but i had the same problem. its build with c#7 as well

**Comment by abbaye** [comment]
Thank you :) if you want put a star on project :)

Humm can you upgrade you project to vs2017 and framework 4.7 ? Normally you can with no problem but I don't know if you have restriction

**Comment by Aitania** [comment]
Thank you Derek... star is already there since days... ;-)

**Comment by abbaye** [comment]
Thank you sir :)

Yes there are a lot but not for wpf :) I have spend most of my free time on this project.

Hum it's not possible for me to downgrade version because c# 7.0 is totally integrated in.

**Comment by abbaye** [comment]
It's Not work if you just reference dll compiled for framework 4.5 ? I can make a test this afternoon

**Comment by Aitania** [comment]
I have managed by downloading the old assembly... only the WPFHexaEditor.dll (2.506 kB)

 xmlns:hexEdit="clr-namespace:WPFHexaEditor.**Control**;assembly=WPFHexaEditor"

            <hexEdit:HexaEditor Grid.Row="2"
                               Grid.Column="0"
                               Grid.ColumnSpan="2"
                               Width="Auto"
                               Height="Auto">
            </hexEdit:HexaEditor>

i have to test it ..

**Comment by abbaye** [comment]
Its very old this version... very slow and buggy :(

**Comment by Aitania** [comment]
i have a XamlParseException exception: :-(

**Comment by abbaye** [comment]
It's not your day :( I will check when I have access to my laptop

**Comment by Aitania** [comment]
:-))   :-))   :-))   :-))   :-))

**Comment by abbaye** [comment]
[Lastest version in framework 4.5 - 2017-12-17](https://github.com/abbaye/WpfHexEditorControl/tree/a3b768a99df55d18f6d093301274cbee4eb8095d)

[Lastest version in c# 6.0 - 2017-08-31](https://github.com/abbaye/WpfHexEditorControl/tree/e5f71a66194f2324c413cbc88ce9243f30e17578)

**Comment by Aitania** [comment]
wow... Thank you Derek !!! I will give you a notice when i try it!

**Comment by abbaye** [comment]
It's not the last version but maybe help you 

Best regards !

**Comment by abbaye** [comment]
Can you compile your project on vs2017 ? If yes it's will be correct the biggest problem (compile c# 7.0)

After you can easily modifies my code to change the framework to 4.6

**Comment by Aitania** [comment]
Lastest version in c# 6.0 - 2017-08-31 has more than 300 errors..
Most of them are because the c#7 syntax like
            if (long.TryParse(hex, out long value))            
or
                var isByte = HexToByte(hexValue, out byte b);

**Comment by Aitania** [comment]
same in framework 4.5
1>------ Build started: Project: WPFHexaEditor, Configuration: Debug Any CPU ------
1>CSC : error CS1617: Invalid option 'latest' for /langversion; must be ISO-1, ISO-2, Default or an integer in range 1 to 6.
2>------ Build started: Project: WpfHexEditor.Sample, Configuration: Debug Any CPU ------
2>C:\__Codeproject\_HEX-Editor\WpfHexEditorControl_45\WPFHexaEditorExample\MainWindow.xaml(223,14): error MC3074: The tag 'HexEditor' does not exist in XML namespace 'clr-namespace:WpfHexaEditor;assembly=WPFHexaEditor'. Line 223 Position 14.
========== Build: 0 succeeded, 2 failed, 0 up-to-date, 0 skipped ==========

**Comment by Aitania** [comment]
I have VS 2015... i can only with the Microsoft.Net.Compilers compile it but
then i take a xaml exception
My project is very big and i am sure that some other packages they have to be updated as well.. 
This redisign i want to make it as a future.

**Comment by abbaye** [comment]
Humm ok :( I will think of a solution. I'll come back to you

**Comment by abbaye** [comment]
Did you found a solution at you problem ?

**Comment by abbaye** [comment]
Aitania, take the last code, you will now use with framework 4.5 or 4.7 :)  

Thank to Janus Tida :)
